# Generated by Django 5.0.6 on 2024-07-11 23:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_started', models.BooleanField(default=False)),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(blank=True, max_length=50, null=True)),
                ('chat_history', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
