# Generated by Django 6.0.7 on 2026-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='vs_bot',
            field=models.BooleanField(default=False),
        ),
    ]
